// App config defaults for Kartman's Giant SyncDrive e-bike
// Exported from VESC Tool — these override appconf_default.h via #ifndef guards

#ifndef APPCONF_FLIPSKY_60_EBIKE_H_
#define APPCONF_FLIPSKY_60_EBIKE_H_

// ── ADC (throttle) ──
#define APPCONF_ADC_CTRL_TYPE			ADC_CTRL_TYPE_CURRENT
#define APPCONF_ADC_HYST				0.15
#define APPCONF_ADC_VOLTAGE_START		0.9
#define APPCONF_ADC_VOLTAGE_END			3.0
#define APPCONF_ADC_VOLTAGE_MIN			0.0
#define APPCONF_ADC_VOLTAGE_MAX			3.5
#define APPCONF_ADC_VOLTAGE_CENTER		2.0
#define APPCONF_ADC_VOLTAGE2_START		0.9
#define APPCONF_ADC_VOLTAGE2_END		3.0
#define APPCONF_ADC_USE_FILTER			true
#define APPCONF_ADC_SAFE_START			true
#define APPCONF_ADC_BUTTONS				0
#define APPCONF_ADC_VOLTAGE_INVERTED	false
#define APPCONF_ADC_VOLTAGE2_INVERTED	false
#define APPCONF_ADC_RAMP_TIME_POS		0.3
#define APPCONF_ADC_RAMP_TIME_NEG		0.1
#define APPCONF_ADC_MULTI_ESC			true
#define APPCONF_ADC_TC					false
#define APPCONF_ADC_TC_MAX_DIFF			3000.0
#define APPCONF_ADC_UPDATE_RATE_HZ		500

// ── PAS ──
#define APPCONF_PAS_CTRL_TYPE			PAS_CTRL_TYPE_CADENCE
#define APPCONF_PAS_SENSOR_TYPE			PAS_SENSOR_TYPE_QUADRATURE
#define APPCONF_PAS_CURRENT_SCALING		0.1
#define APPCONF_PAS_PEDAL_RPM_START		10.0
#define APPCONF_PAS_PEDAL_RPM_END		300.0
#define APPCONF_PAS_INVERT_PEDAL_DIRECTION	false
#define APPCONF_PAS_MAGNETS				12
#define APPCONF_PAS_USE_FILTER			true
#define APPCONF_PAS_RAMP_TIME_POS		0.6
#define APPCONF_PAS_RAMP_TIME_NEG		0.3
#define APPCONF_PAS_UPDATE_RATE_HZ		500
#define APPCONF_PAS_MAX_CURRENT			1.0

// ── PAS Follow ──
#define APPCONF_PAS_FOLLOW_START_ROTATIONS		0.05f
#define APPCONF_PAS_FOLLOW_IDLE_TIMEOUT_S		0.6f
#define APPCONF_PAS_FOLLOW_TARGET_LEAD			1.08f
#define APPCONF_PAS_FOLLOW_ERPM_RAMP_RATE		5000.0f
#define APPCONF_PAS_FOLLOW_CADENCE_FILTER		0.15f
#define APPCONF_PAS_FOLLOW_RAMP_DOWN_MULT		5000.0f

#endif // APPCONF_FLIPSKY_60_EBIKE_H_
